### ISSUE TITLE
java.lang.IllegalArgumentException: unexpected url

### ISSUE THREAD

**Issue by Taringanet** [matc4/react-native-svg-uri#13]
I placed the svg on the same directory than the component `.js`, and then:

```
<SvgUri source={require('./logo_white.svg')} />
```

This seems to work ok in debug mode, but when I build the release apk for android it crashes with:

```
java.lang.IllegalArgumentException: unexpected url: components_logo_logo_white
 	at okhttp3.Request$Builder.url(Request.java:141)
 	at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:168)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 	at android.os.Handler.handleCallback(Handler.java:751)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
 	at android.os.Looper.loop(Looper.java:154)
 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
 	at java.lang.Thread.run(Thread.java:761)
Force finishing activity com.app.staging/com.app.MainActivity
```

Any ideas? Am I doing anything wrong?

Thanks!

**Comment by matc4** [comment]
Hi!, apparently there is a problem in Android, when the packager places the resources only accepts images or xml, but no SVG. (this only happen in Android and with static resources). 
There isn't a workarround yet. see #12 


p/s: Congrats for Taringa!, excellent site (I'm from Argentina).

**Comment by matc4** [comment]
I will close this issue. Please follow #12
