### ISSUE TITLE
react-native packager has encountered an internal error

### ISSUE THREAD

**Issue by shaikhussian** [matc4/react-native-svg-uri#41]
Hai, i am trying to import react-native-svg-uri, after install i wrote some code like this
`<SvgUri source = {require('./images/innerBg.svg')} style={{position:'absolute',left:0,width: windowSize.width,height: windowSize.height}}/>`
but it throws an error like this
![simulator screen shot 28-feb-2017 6 53 13 pm](https://cloud.githubusercontent.com/assets/11956308/23406890/3545486a-fde7-11e6-8ef0-b0b3e78c630e.png)
in terminal it show like this
![screen shot 2017-02-28 at 6 54 27 pm](https://cloud.githubusercontent.com/assets/11956308/23406923/5e0b78dc-fde7-11e6-8cd1-19b78360e422.png)

Please give me suggestions that how to solve this error

**Comment by JanErikFoss** [comment]
I have the same error

**Comment by shaikhussian** [comment]
Any one please respond for it

**Comment by jjhesk** [comment]
i got the same thing too.. 
```
nalysing...TypeError: invalid svg
    at Object.calculate (/Users/xxx/Documents/reactnative/rnfirst/node_modules/image-size/lib/types/svg.js:61:13)
    at lookup (/Users/xxx/Documents/reactnative/rnfirst/node_modules/image-size/lib/index.js:27:31)
    at /Users/xxx/Documents/reactnative/rnfirst/node_modules/image-size/lib/index.js:93:22
    at /Users/xx/Documents/reactnative/rnfirst/node_modules/image-size/lib/index.js:50:9
    at /Users/xx/Documents/reactnative/rnfirst/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
Error: not opened
    at WebSocket.send (/Users/xx/Documents/reactnative/rnfirst/node_modules/ws/lib/WebSocket.js:219:16)
    at send (/Users/xx/Documents/reactnative/rnfirst/node_modules/react-native/local-cli/server/util/webSocketProxy.js:26:12)
    at WebSocket.debuggerSocket.onmessage (/Users/xx/Documents/reactnative/rnfirst/node_modules/react-native/local-cli/server/util/webSocketProxy.js:49:46)
    at WebSocket.onMessage (/Users/xx/Documents/reactnative/rnfirst/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/xx/Documents/reactnative/rnfirst/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/xx/Documents/reactnative/rnfirst/node_modules/ws/lib/Receiver.js:536:18
    at /Users/xx/Documents/reactnative/rnfirst/node_modules/ws/lib/Receiver.js:368:7
    at /Users/xx/Documents/reactnative/rnfirst/node_modules/ws/lib/PerMessageDeflate.js:249:5


```

**Comment by AkshatSharda** [comment]
Hi @shaikhussian,
Just give the height="x" weight="y" to the SVG tag of the SVG image.
In your case give height and width to the innerBg.svg

**Comment by shaikhussian** [comment]
@AkshatSharda i tried as per you suggestion, i wrote like this in my code
`<SvgUri source = {require('./images/innerBg.svg')} style={{width:150,height:150}}/>`

but still facing the same error

**Comment by AkshatSharda** [comment]
@shaikhussian I was talking about the svg image (in your case innerBg.svg). That SVG image contain the <svg> tag. Give the height and width to that tag.
for ex:- <svg height="50" width="500">
{other tags}
</svg>

**Comment by ButuzGOL** [comment]
@AkshatSharda works thx

**Comment by marcind** [comment]
This is ultimately caused by react-native package using an old version of image-size library. They have a bug requesting an update here: https://github.com/facebook/react-native/issues/13102
