### ISSUE TITLE
Release 

### ISSUE THREAD

**Issue by AlanFoster** [matc4/react-native-svg-uri#43]
When attempting to [generate a signed apk](https://facebook.github.io/react-native/docs/signed-apk-android.html) and running with `react-native-svg-uri` the following exception occurs when starting up the app for the first time:

```
03-12 18:00:01.133  7044  7064 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
03-12 18:00:01.133  7044  7064 E AndroidRuntime: Process: com.appprototype, PID: 7044
03-12 18:00:01.133  7044  7064 E AndroidRuntime: java.lang.IllegalArgumentException: unexpected url: src_images_containers_images_spinner
03-12 18:00:01.133  7044  7064 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:141)
03-12 18:00:01.133  7044  7064 E AndroidRuntime: 	at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:172)
03-12 18:00:01.133  7044  7064 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-12 18:00:01.133  7044  7064 E AndroidRuntime: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
03-12 18:00:01.133  7044  7064 E AndroidRuntime: 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:136)
03-12 18:00:01.133  7044  7064 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-12 18:00:01.133  7044  7064 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
03-12 18:00:01.133  7044  7064 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-12 18:00:01.133  7044  7064 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-12 18:00:01.133  7044  7064 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-12 18:00:01.133  7044  7064 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
03-12 18:00:01.133  7044  7064 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
```

Versions:

```
"react": "~15.4.1",
"react-native": "0.42.0",
"react-native-svg-uri": "~1.2.0",
```

I assume that this is not an issue with teh `react-native-svg-uri` library itself, but the asset generation side of things. However I thought this might be a good issue to be aware of / document a workaround for it required.

**Comment by prigornitskiy** [comment]
see https://github.com/matc4/react-native-svg-uri/issues/12

**Comment by Lichwa** [comment]
This doesn't work because it's loading svg files using fetch and you can't fetch local filesystem in release version since there is no react packager. Proper way to do it would be to read these files using https://github.com/johanneslumpe/react-native-fs but I couldn't make it work yet.

**Comment by ggepenyan** [comment]
I have the same problem,, Everything is great in emulator, but error throws in device. Can you suggest what can I do pleaase? How can I use svg? I don't know what to do

**Comment by matc4** [comment]
@ggepenyan  See #12. Its a known bug.
